#!/usr/bin/env python
# -*- python -*-

"""
cnq - enqueue files and URLs into cplay
Copyright (C) 2009 Tom Adams <tom@holizz.com>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
"""

import os, sys

CONTROL_FIFO = "%s/cplay-control-%s" % (os.environ.get("TMPDIR", "/tmp"), os.environ["USER"])

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print('Arguments, please.')
        sys.exit(1)
    if os.path.exists(CONTROL_FIFO):
        fd = open(CONTROL_FIFO, "wb", 0)
        for a in sys.argv[1:]:
            if not a.startswith('http'):
                a = os.path.abspath(os.path.curdir) + '/' + a
            fd.write('add %s\n' % a)
        fd.close()
    else:
        print('Could not find %s.' % CONTROL_FIFO)
        sys.exit(2)
