.\" Copyright (C) 2000 Martin Michlmayr <tbm@cyrius.com>
.\" This manual is freely distributable under the terms of the GPL.
.\" It was originally written for Debian GNU/Linux (but may be used
.\" by others).
.\"
.TH CPLAY 1 "December 2001"

.SH NAME
.PP
cplay \- a front-end for various audio players

.SH SYNOPSIS
.PP
\fBcplay\fR [-options] [ \fIfile\fP | \fIdir\fP |\fIplaylist.m3u\fP ] ...

.SH DESCRIPTION
.PP
.B cplay
is a front-end for various audio players. It aims to provide a
user-friendly interface with simple filelist and playlist
control.  Invoking
.B cplay
without any options puts you in the filelist in which you
can navigate around looking for audio files.  When you
specify an audio file,
.B cplay
automatically adds it to the playlist which can be accessed
by pressing the tabulator key.
.PP
Currently, the folloging audio formats are supported: MP3 (through
mpg321, splay, mpg123 or madplay), Ogg Vorbis (through ogg123), and
various module-formats (through mikmod).

.SH OPTIONS
.IP \fB-r
Toggles playlist \fIrepeat\fP mode
.IP \fB-R
Toggles playlist \fIrandom\fP mode

.SH SEE ALSO
.PP
.BR ogg123 (1),
.BR mpg123 (1),
.BR mpg321 (1),
.BR splay (1),
.BR madplay (1),
.BR mikmod (1)

.SH AUTHOR
.PP
Ulf Betlehem <flu@iki.fi>

