.\" Copyright (C) 2000, 2002 Martin Michlmayr <tbm@cyrius.com>
.\" This manual is freely distributable under the terms of the GPL.
.\" It was originally written for Debian GNU/Linux (but may be used
.\" by others).
.\"
.TH CPLAY 1 "September 2014"

.SH NAME
.PP
cplay \- a front-end for various audio players

.SH SYNOPSIS
.PP
\fBcplay\fR [\-options] [ \fIfile\fP | \fIdir\fP | \fIplaylist\fP ] ...

.SH DESCRIPTION
.PP
.B cplay
is a front-end for various audio players. It aims to provide a minimal
interface with simple filelist and playlist control. Invoking
.B cplay
without any options puts you in the filelist in which you can navigate around
with the arrow keys looking for audio files.  When you select an audio file, it
can either be played directly (press enter), or added to the playlist
(press 'a'). The playlist can be accessed by pressing the tab key.
.PP
Use 'h' to display the help window explaining other keyboard shortcuts.
.PP
Shell command lines can be executed with tagged or current entries as
positional parameters by specifying "$@".
.PP
Currently, the following audio formats are supported: MP3 (through mpg321,
splay, mpg123 or madplay), Ogg Vorbis (through ogg123), and various other
formats (through mplayer, gst123, mikmod, and xmp).

.SH OPTIONS
.IP \fB\-n
Enable \fIrestricted\fI mode
.IP \fB\-r
Toggles playlist \fIrepeat\fP mode
.IP \fB\-R
Toggles playlist \fIrandom\fP mode
.IP \fB\-v
Toggles PCM and MASTER (default) volume control

.SH REMOTE CONTROL FILE
.B cplay
can be controlled through a FIFO.
.PP
Available commands:
.PP
play
.br
stop
.br
pause
.br
next
.br
prev
.br
empty
.br
quit
.br
forward \fIseconds\fR
.br
backward \fIseconds\fR
.br
add \fIfile\fR
.br
volume set \fIpercentage\fR
.br
macro \fIname\fR
.PP
Example:
.PP
\fBecho pause >/tmp/cplay-control-$USER\fB

.SH SEE ALSO
.PP
.BR mplayer (1),
.BR gst123 (1),
.BR ogg123 (1),
.BR mpg123 (1),
.BR mpg321 (1),
.BR splay (1),
.BR madplay (1),

.SH FILES
.PP
.I /tmp/cplay-control-$USER
- Optional remote control fifo.

.SH AUTHOR
.PP
Ulf Betlehem <flu@iki.fi>

